import Head from 'next/head'
import '../styles/globals.css'
import {LightgalleryProvider} from "react-lightgallery"
import "lightgallery.js/dist/css/lightgallery.css"

function MyApp({ Component, pageProps }) {
  return (
    <LightgalleryProvider 
    lightgallerySettings={ { 'download':false } }
    >
      <Head> <title>craigmadethis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Component {...pageProps} />
    </LightgalleryProvider>

  )
}

export default MyApp
